---
- name: test the cloud
  hosts: cloud
  vars:
    localrc_address: http://goo.gl/OeOGqL
  tasks:
    - name: install git
      sudo: True
      apt: name=git
    - name: set the time zone variables
      sudo: True
      copy: >
        content='America/New_York'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
      notify:
        - update time zone
    - name: creating a tenant
      keystone_user_custom: > 
        tenant=sandbox1
        tenant_description="tenant for user1" 
        login_tenant_name=admin
        login_user=admin
        login_password=secret123
    - name: assiggn user to the tenat
      keystone_user_custom: >
        user=user1 
        tenant=sandbox1
        password=user1
        login_tenant_name=admin
        login_user=admin
        login_password=secret123 
    #  keystone_user: user=test tenant=lab password=test
    #- name: apply the admin role to the test user
    #  keystone_user: role=admin user=test tenant=lab
  handlers:
    - name: update time zone
      sudo: True
      command: dpkg-reconfigure --frontend noninteractive tzdata