---
- name: test the cloud
  hosts: cloud
  #gather_facts: no
  vars:
    localrc_address: http://goo.gl/OeOGqL
  tasks:
    - name: sourcing the file
      command: chdir=/home/ubuntu/icehouse "source openrc.sh"
    - name: creating a tenant
      command: keystone user-list
      environment:
          OS_USERNAME: admin
          OS_TENANT_NAME: demo
          OS_AUTH_URL: http://127.0.0.1:5000/v2.0
          OS_PASSWORD: openstack
    - name: test teh system
      keystone_user_custom: >
        user=ali 
        tenant=demo 
        password=juniper
        login_tenant_name=demo
        login_user=admin
        login_password=openstack
      environment:
          OS_USERNAME: admin
          OS_TENANT_NAME: demo
          OS_AUTH_URL: http://127.0.0.1:5000/v2.0
          OS_PASSWORD: openstack
    #- name: Create a user in keystone
    #  keystone_user: user=test tenant=lab password=test
    #- name: apply the admin role to the test user
    #  keystone_user: role=admin user=test tenant=lab
  handlers:
    - name: update time zone
      sudo: True
      command: dpkg-reconfigure --frontend noninteractive tzdata